<?php
/**
 * @file dh_core.install
 * Install, update and uninstall functions.
 */

/**
 * Implements hook_install().
 */
function dh_core_install() {
  variable_set('admin_theme', 'seven');
  variable_set('node_admin_theme', 1);
}

/**
 * Set admin theme
 */
function dh_core_update_7001() {
  variable_set('admin_theme', 'seven');
  variable_set('node_admin_theme', 1);
}

/**
 * Enable panels_everywhere
 */
function dh_core_update_7002() {
  module_enable(array('panels_everywhere'), TRUE);
}

